### ISSUE TITLE
RabbitMQ: Schlockmeister - Picking up relevant messages

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/python-zocalo#70]
Schlockmeister subscribes to all queues with active subscribers with a selector `JMSXDeliveryCount>5`, which means that although it subscribes to the queue it will only receive messages that have already been delivered more than 5 times:
https://github.com/DiamondLightSource/python-zocalo/blob/d4bc255f179d83839f7d0c6129242ca0c6ff0b69/zocalo/service/schlockmeister.py#L186-L194

We need to find out how we can do something equivalent on RabbitMQ

**Comment by d-j-hatton** [comment]
RabbitMQ does not provide a count of the number of times a message has been requeued for a classic queue. This issue was raised at [https://github.com/rabbitmq/rabbitmq-server/issues/502](url) but redelivery counts and redelivery limits were only implemented for quorum queues. 

Messages are flagged with a bool if they have been redelivered. There is also a count available for the number of times a message is dead-lettered for the same reason. The combination of these two could provide a way to deal with limiting the number of requeues. Consumers could dead-letter redelivered messages and a service could then consume from the dead-letter queue and requeue the message if it has only been dead-lettered a number of times under some threshold, discarding if it exceeds the threshold.

**Comment by Anthchirp** [comment]
As things stand Schlockmeister can be retired with the move to RabbitMQ
